import { Project } from "../types";

export const PROJECTS: Project[] = [
  {
    title: 'Agro AI',
    date: '2025',
    subtext: 'Smart farming: crop rec, disease detection, weather, market prices, voice + multi-lang. React, FastAPI, Python, PostgreSQL.',
    url: 'https://github.com/gajbhiyes774/agro-ai',
  },
  {
    title: 'WhatsApp AI Assistant',
    date: '2025',
    subtext: 'WhatsApp bot with local LLM (Ollama), Node.js, Express, WhatsApp Web.js.',
    url: 'https://github.com/gajbhiyes774/whatsapp-ai',
  },
  {
    title: 'Guardian AI',
    date: '2025',
    subtext: 'Community safety: SOS, missing person (YOLO), volunteer/NGO, blood match. React, FastAPI, Firebase.',
    url: 'https://github.com/gajbhiyes774/guardian-ai',
  },
  {
    title: 'AI Recruiter',
    date: '2024',
    subtext: 'Resume analysis + AI interviews + ranking. React, FastAPI, LLM APIs.',
    url: 'https://github.com/gajbhiyes774/ai-recruiter',
  },
  {
    title: 'Jarvis AI Assistant',
    date: '2024',
    subtext: 'Desktop voice assistant: system control, speech, local LLM (Ollama), Python.',
    url: 'https://github.com/gajbhiyes774/jarvis-ai',
  },
  // ── Open Source — What They Do (20) ──
  {
    title: 'LangGraph 101',
    date: 'MIT • Tutorial',
    subtext: 'Learn LangGraph/LangChain fundamentals: agents, tools, memory, streaming, middleware, DeepAgents. Hands-on notebooks.',
    url: 'https://github.com/gajbhiyes774/langgraph-101',
  },
  {
    title: 'Open SWE',
    date: 'MIT • Agent',
    subtext: 'Autonomous coding agent framework on DeepAgents/LangGraph — plans, implements in sandbox, validates, opens PRs. GitHub/Slack triggers.',
    url: 'https://github.com/gajbhiyes774/open-swe',
  },
  {
    title: 'Browser Use',
    date: 'MIT • Automation',
    subtext: 'Makes websites accessible for AI agents. Automates tasks via Chromium CDP + LLM loop. Batch-ready, cloud browsers.',
    url: 'https://github.com/gajbhiyes774/browser-use',
  },
  {
    title: 'MCP Servers',
    date: 'Apache-2.0 • Protocol',
    subtext: 'Reference Model Context Protocol servers: Everything, Fetch, Filesystem, Git, Memory, Sequential Thinking. SDK demos.',
    url: 'https://github.com/gajbhiyes774/servers',
  },
  {
    title: 'Qdrant',
    date: 'Apache-2.0 • Vector DB',
    subtext: 'Vector similarity search engine in Rust. Stores vectors + payload, filtered search, gRPC/REST. Production-ready.',
    url: 'https://github.com/gajbhiyes774/qdrant',
  },
  {
    title: 'GraphRAG',
    date: 'MIT • RAG',
    subtext: 'Microsoft graph-based RAG: extracts knowledge graphs from unstructured text via LLMs for deep document Q&A. (Maintenance mode)',
    url: 'https://github.com/gajbhiyes774/graphrag',
  },
  {
    title: 'Docling',
    date: 'MIT • Docs',
    subtext: 'Converts PDF/DOCX/HTML/Markdown/audio/images into unified DoclingDocument for AI apps. IBM, 2.126.0.',
    url: 'https://github.com/gajbhiyes774/docling',
  },
  {
    title: 'Ragas',
    date: 'Apache-2.0 • Eval',
    subtext: 'LLM evaluation toolkit: Faithfulness, AnswerCorrectness, ContextPrecision/Recall, test generation. For RAG/LLM apps.',
    url: 'https://github.com/gajbhiyes774/ragas',
  },
  {
    title: 'Langfuse',
    date: 'MIT • Observability',
    subtext: 'LLM engineering platform: tracing, evals, prompt management, analytics. Self-host via Docker (ClickHouse/Postgres).',
    url: 'https://github.com/gajbhiyes774/langfuse',
  },
  {
    title: 'NeMo Guardrails',
    date: 'Apache-2.0 • Safety',
    subtext: 'NVIDIA toolkit for programmable guardrails via Colang: topical rails, jailbreak detection, hallucination control.',
    url: 'https://github.com/gajbhiyes774/Guardrails',
  },
  {
    title: 'Unsloth',
    date: 'Apache-2.0 • Fine-Tune',
    subtext: '2× faster fine-tuning, 70% less VRAM. Trains Qwen/Llama up to 500K context, FP8/VLM RL. RTX 3050 verified.',
    url: 'https://github.com/gajbhiyes774/unsloth',
  },
  {
    title: 'vLLM',
    date: 'Apache-2.0 • Serving',
    subtext: 'Fast LLM inference: PagedAttention, continuous batching, FlashAttention, quantization (FP8/NVFP4). Berkeley.',
    url: 'https://github.com/gajbhiyes774/vllm',
  },
  {
    title: 'LiteLLM',
    date: 'MIT • Gateway',
    subtext: 'AI Gateway unifying 100+ LLMs under OpenAI API: proxy, load balancing, fallbacks, Spend tracking. Rust core.',
    url: 'https://github.com/gajbhiyes774/litellm',
  },
  {
    title: 'Evidently',
    date: 'Apache-2.0 • ML Monitor',
    subtext: 'ML & LLM observability: drift detection, performance monitoring, debug reports for production models.',
    url: 'https://github.com/gajbhiyes774/evidently',
  },
  {
    title: 'Feast',
    date: 'Apache-2.0 • Feature Store',
    subtext: 'Open feature store for ML: define, serve, monitor features for training & online inference. Go/Python/Java.',
    url: 'https://github.com/gajbhiyes774/feast',
  },
  {
    title: 'Text-to-SQL Agent',
    date: 'Agent • Demo',
    subtext: 'Natural language → SQL on Chinook DB via LangChain + Claude Sonnet 4.5. Validates, corrects queries, LangSmith tracing.',
    url: 'https://github.com/langchain-ai/text-to-sql-agent',
  },
  {
    title: 'PR Agent',
    date: 'Apache-2.0 • Code Review',
    subtext: 'AI PR review for GitHub/GitLab/Bitbucket: /review, /describe, /improve, /ask. Dynaconf + LiteLLM.',
    url: 'https://github.com/gajbhiyes774/pr-agent',
  },
  {
    title: 'Pipecat',
    date: 'BSD-2 • Voice',
    subtext: 'Real-time voice/multimodal framework: frame pipeline, 60+ STT/TTS/LLM services, Daily/LiveKit transports.',
    url: 'https://github.com/gajbhiyes774/pipecat',
  },
  {
    title: 'Ultralytics',
    date: 'AGPL-3.0 • Vision',
    subtext: 'YOLO26/11/8: detect, segment, pose, obb — train/val/predict/track/export 20 formats. PyTorch.',
    url: 'https://github.com/gajbhiyes774/ultralytics',
  },
  {
    title: 'Eliza',
    date: 'MIT • Agents OS',
    subtext: 'Agentic operating system in TypeScript (Node 23). Multi-agent, plugins, clients — heavy monorepo.',
    url: 'https://github.com/gajbhiyes774/eliza',
  },
  {
    title: 'Skills & Technologies',
    date: 'Stack',
    subtext: 'Python • JS/TS • React • Next.js • Tailwind • FastAPI • Node • PostgreSQL • MySQL • Firebase • Docker • Linux • LLMs • Ollama • LangChain • YOLO • OCR • Hugging Face',
    url: 'https://github.com/gajbhiyes774',
  },
];
