import { Project } from "../types";

export const PROJECTS: Project[] = [
  {
    title: 'Agro AI',
    date: '2025',
    subtext: 'Crop recommendation (NPK, pH, rainfall, temperature, humidity) + plant disease detection (early/late blight, leaf rust, powdery mildew, healthy) for 10 crops (rice, maize, cotton, sugarcane, wheat, chickpea, mango, apple, banana, coffee). FastAPI (port 8002) + Next.js 16 frontend. Real-time LLM analysis via Ollama.',
    url: 'https://github.com/gajbhiyes774/agro-ai',
  },
  {
    title: 'WhatsApp AI Assistant',
    date: '2025',
    subtext: 'WhatsApp bot using whatsapp-web.js with local LLM (Ollama gemma3:latest) for natural conversational responses. Built with Node.js, Express, session management, and QR-code pairing. No cloud dependency — fully local.',
    url: 'https://github.com/gajbhiyes774/whatsapp-ai',
  },
  {
    title: 'Guardian AI',
    date: '2025',
    subtext: 'Community safety platform: citizen SOS reporting, YOLO object detection for incident photos, real-time volunteer alerts via Socket.io + Firebase RTDB, blood donation matching (geolocation + blood group compatibility), NGO dashboard. Next.js + FastAPI + Firebase.',
    url: 'https://github.com/gajbhiyes774/guardian-ai',
  },
  {
    title: 'AI Recruiter',
    date: '2024',
    subtext: 'Resume parser (PDF/DOCX/TXT) with LLM-based structured extraction + job matching scores. Mock interview simulator: generates technical/behavioral questions, evaluates answers with LLM feedback, provides scored results. FastAPI + Next.js.',
    url: 'https://github.com/gajbhiyes774/ai-recruiter',
  },
  {
    title: 'Jarvis AI Assistant',
    date: '2024',
    subtext: 'Desktop AI assistant using Ollama for local LLM inference with system control capabilities (file ops, app launch, custom commands). Built with Electron/React frontend, Python backend, persistent memory, and voice interaction.',
    url: 'https://github.com/gajbhiyes774/jarvis-ai',
  },
  // ── Open Source — What They Do (20) ──
  {
    title: 'LangGraph 101',
    date: 'MIT • Tutorial',
    subtext: 'Hands-on tutorials for LangGraph/LangChain/Deep Agents: build first agent (models, tools, memory, streaming), middleware, multi-agent supervisor, deep research agent with skills/backends/HITL. 101 (fundamentals) + 201 (production patterns).',
    url: 'https://github.com/gajbhiyes774/langgraph-101',
  },
  {
    title: 'Open SWE',
    date: 'MIT • Agent',
    subtext: 'Asynchronous coding agent built on Deep Agents + LangGraph: investigates repo → plans → implements in isolated Linux sandbox → validates with tests → delivers PR. Supports GitHub/Slack/Linear triggers, read-only reviewer, CI monitoring, scheduling. 5 graph entrypoints (agent/reviewer/analyzer/chat/scheduler).',
    url: 'https://github.com/gajbhiyes774/open-swe',
  },
  {
    title: 'Browser Use',
    date: 'MIT • Automation',
    subtext: 'AI browser automation framework: autonomous web navigation via Chromium (CDP). Agent takes task → navigates pages → extracts content → repeats LLM loop until done. Tools: search/navigate/click/input/scroll/extract/screenshot. Supports cloud browsers + profile sync + proxy stealth.',
    url: 'https://github.com/gajbhiyes774/browser-use',
  },
  {
    title: 'MCP Servers',
    date: 'Apache-2.0 • Protocol',
    subtext: 'Reference implementations for the Model Context Protocol (MCP): everything (test server), fetch (web content), filesystem (secure file access), git (repo operations), memory (knowledge graph), sequential-thinking (dynamic reasoning), time (timezone). TypeScript SDK demos.',
    url: 'https://github.com/gajbhiyes774/servers',
  },
  {
    title: 'Qdrant',
    date: 'Apache-2.0 • Vector DB',
    subtext: 'Production-ready vector database in Rust: high-performance similarity search with extended filtering, faceted search, recommendations. REST (6333) and gRPC (6334) APIs. Stores vectors + payload. Used for semantic matching, RAG embeddings.',
    url: 'https://github.com/gajbhiyes774/qdrant',
  },
  {
    title: 'GraphRAG',
    date: 'MIT • RAG',
    subtext: 'Microsoft research project: graph-based RAG that builds knowledge graphs from unstructured private text via LLMs, enabling deep narrative Q&A with targeted context. Includes indexing pipeline, query, prompt tuning. (Maintenance mode — bug fixes/dependency updates only.)',
    url: 'https://github.com/gajbhiyes774/graphrag',
  },
  {
    title: 'Docling',
    date: 'MIT • Documents',
    subtext: 'IBM-backed document conversion SDK: parses PDF, DOCX, HTML, Markdown, audio, images, XML into unified `DoclingDocument` for AI workflows (RAG, data extraction). Python package + CLI (`docling convert`). Supports layout detection, table extraction, OCR.',
    url: 'https://github.com/gajbhiyes774/docling',
  },
  {
    title: 'Ragas',
    date: 'Apache-2.0 • Evaluation',
    subtext: 'LLM evaluation toolkit: objective metrics for RAG/LLM apps — Faithfulness, AnswerCorrectness, ContextPrecision/Recall, AspectCritic, and automated test data generation. Integrates with LangChain + LlamaIndex. For benchmarking model outputs.',
    url: 'https://github.com/gajbhiyes774/ragas',
  },
  {
    title: 'Langfuse',
    date: 'MIT • Observability',
    subtext: 'Open-source LLM engineering platform: tracing, evaluation, prompt management, analytics, debugging for AI apps. Self-host with Postgres + ClickHouse (Docker Compose). Provides LangSmith-style observability.',
    url: 'https://github.com/gajbhiyes774/langfuse',
  },
  {
    title: 'NeMo Guardrails',
    date: 'Apache-2.0 • Safety',
    subtext: 'NVIDIA toolkit for programmable LLM guardrails via Colang: topical consent rules, jailbreak detection, output filtering, fact-checking. Prevents harmful/inappropriate LLM responses. For production AI safety.',
    url: 'https://github.com/gajbhiyes774/Guardrails',
  },
  {
    title: 'Unsloth',
    date: 'Apache-2.0 • Fine-Tune',
    subtext: 'Fast LLM fine-tuning library: 2× faster training, 70% less VRAM. Quantized models (Qwen3.6, Llama, etc.) with MTP, NVFP4, FP8, vision RL. 500K context on 80GB GPU; works on RTX 3050 for small models.',
    url: 'https://github.com/gajbhiyes774/unsloth',
  },
  {
    title: 'vLLM',
    date: 'Apache-2.0 • Serving',
    subtext: 'High-throughput LLM inference server: PagedAttention, continuous batching, chunked prefill, FlashAttention, quantization (INT8/INT4/GPTQ/AWQ/GGUF). Built at Berkeley — used for production-scale model serving.',
    url: 'https://github.com/gajbhiyes774/vllm',
  },
  {
    title: 'LiteLLM',
    date: 'MIT • Gateway',
    subtext: 'Fast AI Gateway (Rust core) unifying 100+ LLM providers (OpenAI, Anthropic, Gemini, Bedrock, Azure, etc.) under a single OpenAI-compatible API. Supports load balancing, fallbacks, Spend tracking, proxy.',
    url: 'https://github.com/gajbhiyes774/litellm',
  },
  {
    title: 'Evidently',
    date: 'Apache-2.0 • Monitor',
    subtext: 'Open-source ML & LLM observability: drift detection, performance diagnostics, debug reports, data quality checks. For production model monitoring (scikit-learn compatible).',
    url: 'https://github.com/gajbhiyes774/evidently',
  },
  {
    title: 'Feast',
    date: 'Apache-2.0 • Feature Store',
    subtext: 'Open-source feature store: define, serve, and monitor ML features for training and online inference. Python/Go/Java SDK + PostgreSQL + Redis. Used by ML pipelines.',
    url: 'https://github.com/gajbhiyes774/feast',
  },
  {
    title: 'Text-to-SQL Agent',
    date: 'Agent • Demo',
    subtext: 'Natural-language to SQL conversion using LangChain + Anthropic Claude Sonnet 4.5, validated on Chinook DB. Includes query validation, error correction, LangSmith tracing.',
    url: 'https://github.com/langchain-ai/text-to-sql-agent',
  },
  {
    title: 'PR Agent',
    date: 'Apache-2.0 • Review',
    subtext: 'AI-powered PR reviews for GitHub/GitLab/Bitbucket: /review, /describe, /improve, /ask commands. Learn repository-specific review style. Dynaconf settings.',
    url: 'https://github.com/gajbhiyes774/pr-agent',
  },
  {
    title: 'Pipecat',
    date: 'BSD-2 • Voice',
    subtext: 'Real-time voice and multimodal conversational AI framework. Frame pipeline with 60+ AI services (STT/TTS/LLM). Daily/LiveKit transport, WebSocket. For production voice bots.',
    url: 'https://github.com/gajbhiyes774/pipecat',
  },
  {
    title: 'Ultralytics',
    date: 'AGPL-3.0 • Vision',
    subtext: 'YOLO family (YOLO26/11/8) for detection, segmentation, pose, oriented boxes, tracking. Train/val/predict/export 20 formats. PyTorch-based, supports CPU and GPU.',
    url: 'https://github.com/gajbhiyes774/ultralytics',
  },
  {
    title: 'Eliza',
    date: 'MIT • Agents OS',
    subtext: 'Open-source agentic operating system (TypeScript, Bun, Turbo). Multi-agent framework with plugins, channels, memory, and UI. Built for scalable AI agent hosts.',
    url: 'https://github.com/gajbhiyes774/eliza',
  },
  {
    title: 'Skills & Technologies',
    date: 'Stack',
    subtext: 'Python • TypeScript • React • Next.js • Tailwind • FastAPI • Node.js • PostgreSQL • Firebase • Docker • Linux • LLMs • Ollama • LangChain • YOLO • OCR • Hugging Face',
    url: 'https://github.com/gajbhiyes774',
  },
];
