import { Project } from "../types";

export const PROJECTS: Project[] = [
  {
    title: 'Agro AI',
    date: '2025',
    subtext: 'Smart farming: crop rec, disease detection, weather, market prices, voice + multi-lang. React, FastAPI, Python, PostgreSQL.',
    url: 'https://github.com/gajbhiyes774/agro-ai',
  },
  {
    title: 'WhatsApp AI Assistant',
    date: '2025',
    subtext: 'WhatsApp bot with local LLM (Ollama), Node.js, Express, WhatsApp Web.js.',
    url: 'https://github.com/gajbhiyes774/whatsapp-ai',
  },
  {
    title: 'Guardian AI',
    date: '2025',
    subtext: 'Community safety: SOS, missing person (YOLO), volunteer/NGO, blood match. React, FastAPI, Firebase.',
    url: 'https://github.com/gajbhiyes774/guardian-ai',
  },
  {
    title: 'AI Recruiter',
    date: '2024',
    subtext: 'Resume analysis + AI interviews + ranking. React, FastAPI, LLM APIs.',
    url: 'https://github.com/gajbhiyes774/ai-recruiter',
  },
  {
    title: 'Jarvis AI Assistant',
    date: '2024',
    subtext: 'Desktop voice assistant: system control, speech, local LLM (Ollama), Python.',
    url: 'https://github.com/gajbhiyes774/jarvis-ai',
  },
  // ── Open Source — Setup & Integration (20 forks) ──
  {
    title: 'LangGraph 101',
    date: 'MIT • Fork',
    subtext: 'Original: langchain-ai/langgraph-101. My Fork: gajbhiyes774/langgraph-101. LangChain/LangGraph tutorials. Work: Ollama setup, docs.',
    url: 'https://github.com/gajbhiyes774/langgraph-101',
  },
  {
    title: 'Open SWE',
    date: 'MIT • Fork',
    subtext: 'Original: langchain-ai/open-swe. Fork: gajbhiyes774/open-swe. Async coding agent. Work: Rust diagnosis, env template. (Windows blocked)',
    url: 'https://github.com/gajbhiyes774/open-swe',
  },
  {
    title: 'Browser Use',
    date: 'MIT • Fork',
    subtext: 'Original: browser-use/browser-use. Fork: gajbhiyes774/browser-use. AI browser automation. Work: uv + Chromium, tests (1193).',
    url: 'https://github.com/gajbhiyes774/browser-use',
  },
  {
    title: 'MCP Servers',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: modelcontextprotocol/servers. Fork: gajbhiyes774/servers. Reference MCP servers. Work: npm build, stdio test.',
    url: 'https://github.com/gajbhiyes774/servers',
  },
  {
    title: 'Qdrant',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: qdrant/qdrant. Fork: gajbhiyes774/qdrant. Vector DB (Rust). Work: Docker diagnosis.',
    url: 'https://github.com/gajbhiyes774/qdrant',
  },
  {
    title: 'GraphRAG',
    date: 'MIT • Fork',
    subtext: 'Original: microsoft/graphrag. Fork: gajbhiyes774/graphrag. Graph RAG (maintenance mode). Work: Rust diagnosis.',
    url: 'https://github.com/gajbhiyes774/graphrag',
  },
  {
    title: 'Docling',
    date: 'MIT • Fork',
    subtext: 'Original: docling-project/docling. Fork: gajbhiyes774/docling. Doc → DoclingDocument (2.126.0). Work: pip + convert test.',
    url: 'https://github.com/gajbhiyes774/docling',
  },
  {
    title: 'Ragas',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: vibrantlabsai/ragas. Fork: gajbhiyes774/ragas. LLM evals (0.4.3). Work: pip + compat fix.',
    url: 'https://github.com/gajbhiyes774/ragas',
  },
  {
    title: 'Langfuse',
    date: 'MIT • Fork',
    subtext: 'Original: langfuse/langfuse. Fork: gajbhiyes774/langfuse. LLM observability (Docker). Work: Docker diagnosis.',
    url: 'https://github.com/gajbhiyes774/langfuse',
  },
  {
    title: 'NeMo Guardrails',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: NVIDIA-NeMo/Guardrails. Fork: gajbhiyes774/Guardrails. LLM guardrails (0.24.0). Work: pip + import test.',
    url: 'https://github.com/gajbhiyes774/Guardrails',
  },
  {
    title: 'Unsloth',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: unslothai/unsloth. Fork: gajbhiyes774/unsloth. Fast LLM fine-tune. GPU: RTX 3050 (4GB). Work: Docker diagnosis.',
    url: 'https://github.com/gajbhiyes774/unsloth',
  },
  {
    title: 'vLLM',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: vllm-project/vllm. Fork: gajbhiyes774/vllm. Fast LLM serving (PagedAttention). Work: GPU verify, uv docs.',
    url: 'https://github.com/gajbhiyes774/vllm',
  },
  {
    title: 'LiteLLM',
    date: 'MIT • Fork',
    subtext: 'Original: BerriAI/litellm. Fork: gajbhiyes774/litellm. AI Gateway (1.99.0). Work: pip + CLI test.',
    url: 'https://github.com/gajbhiyes774/litellm',
  },
  {
    title: 'Evidently',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: evidentlyai/evidently. Fork: gajbhiyes774/evidently. ML observability (0.7.21). Work: pip + import.',
    url: 'https://github.com/gajbhiyes774/evidently',
  },
  {
    title: 'Feast',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: feast-dev/feast. Fork: gajbhiyes774/feast. Feature Store (0.66.0). Work: pip + CLI.',
    url: 'https://github.com/gajbhiyes774/feast',
  },
  {
    title: 'Text-to-SQL Agent',
    date: 'NOASSERTION',
    subtext: 'Original: langchain-ai/text-to-sql-agent (no LICENSE). Local only — not forked. Work: pip + CLI test.',
    url: 'https://github.com/langchain-ai/text-to-sql-agent',
  },
  {
    title: 'PR Agent',
    date: 'Apache-2.0 • Fork',
    subtext: 'Original: Codium-ai/pr-agent. Fork: gajbhiyes774/pr-agent (0.2.4). PR review AI. Work: --no-deps + docs.',
    url: 'https://github.com/gajbhiyes774/pr-agent',
  },
  {
    title: 'Pipecat',
    date: 'BSD-2 • Fork',
    subtext: 'Original: pipecat-ai/pipecat. Fork: gajbhiyes774/pipecat. Real-time voice (1.8.1). Work: pip + Pipeline test.',
    url: 'https://github.com/gajbhiyes774/pipecat',
  },
  {
    title: 'Ultralytics',
    date: 'AGPL-3.0 • Fork',
    subtext: 'Original: ultralytics/ultralytics. Fork: gajbhiyes774/ultralytics. YOLO (8.4.137). Work: pip + yolo help.',
    url: 'https://github.com/gajbhiyes774/ultralytics',
  },
  {
    title: 'Eliza',
    date: 'MIT • Fork',
    subtext: 'Original: elizaOS/eliza. Fork: gajbhiyes774/eliza. Agentic OS (Node 23). Work: fork + disk-full diagnosis.',
    url: 'https://github.com/gajbhiyes774/eliza',
  },
  {
    title: 'Skills & Technologies',
    date: 'Stack',
    subtext: 'Python • JS/TS • React • Next.js • Tailwind • FastAPI • Node • PostgreSQL • MySQL • Firebase • Docker • Linux • LLMs • Ollama • LangChain • YOLO • OCR • Hugging Face',
    url: 'https://github.com/gajbhiyes774',
  },
];
